### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by htmlgod** [htmlgod/cpp-project-template#1]
- [ ]  add coverage and other tools
- [ ]  add CPACK config
- [ ]  add artifacts build (github)
- [ ]  github branches settings
